# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6cAU8ZHZ4fIAD7z7j1-xadGttdYvTLB
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# --- 1. Data Sampel (Luas Tanah vs Harga Rumah) ---
# X = Luas Tanah (m2), y = Harga (Juta Rupiah)
X = np.array([[60], [72], [100], [120], [150], [180], [200], [250]])
y = np.array([[300], [360], [550], [620], [800], [950], [1100], [1350]])

# --- 2. Membuat Model Regresi Linear ---
model = LinearRegression()
model.fit(X, y)

# --- 3. Melakukan Prediksi ---
X_test = np.array([[130], [220]]) # Kita ingin prediksi harga untuk tanah 130m2 dan 220m2
y_pred = model.predict(X_test)

print(f"Koefisien (Slope): {model.coef_[0][0]}")
print(f"Intercept: {model.intercept_[0]}")

# --- 4. Visualisasi Data (Penting untuk Video) ---
plt.scatter(X, y, color='blue', label='Data Asli')
plt.plot(X, model.predict(X), color='red', label='Garis Regresi')
plt.scatter(X_test, y_pred, color='green', marker='x', s=100, label='Prediksi Baru')

plt.title('Prediksi Harga Rumah (Regresi Linear)')
plt.xlabel('Luas Tanah (m2)')
plt.ylabel('Harga (Juta Rupiah)')
plt.legend()
plt.grid(True)
plt.show()

